import sqlite3
conn=sqlite3.connect("Training_data.db")
conn.execute("delete from Data;")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Sunny','Hot','High','Weak','No');")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Sunny','Hot','High','Strong','No');")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Overcast','Hot','High','Weak','Yes');")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Rainy','Mild','High','Weak','Yes');")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Rainy','Cool','Normal','Weak','Yes');")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Rainy','Cool','Normal','Strong','No');")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Overcast','Cool','Normal','Strong','Yes');")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Sunny','Mild','High','Weak','No');")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Sunny','Cool','Normal','Weak','Yes');")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Rainy','Mild','Normal','Weak','Yes');")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Sunny','Mild','Normal','Strong','Yes');")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Overcast','Mild','High','Strong','Yes');")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Overcast','Hot','Normal','Weak','Yes');")
conn.execute("insert into Data(outlook, temperature, humidity, wind, result) values('Rainy','Mild','High','Strong','No');")
conn.commit()
print("Data entered succesfully")